name: Cypress e2e Test

on: push

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: run end-to-end cypress test
        id: run_end_to_end_cypress_test
        uses: cypress-io/github-action@v6
        with:
          build: pnpm run build
          start: pnpm run start
          browser: chrome
        env:
          IS_CI: true
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
